[package]
name = "esp32-chip-quest-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version="0.20", features=["csr"] }


[profile.release]
# Optimize for size.
opt-level = "z"


